services:
  server:
    container_name: gemini
    build: 
      context: .
      dockerfile: Dockerfile_database
    ports:
      - "80:80"
    volumes:
      - shared-data:/cont/dbsql
      - ./src:/cont/src
      - /home/admin/mentees:/mnt/mentees

  db:
    container_name: database
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=gemini
      - MYSQL_ROOT_PASSWORD=root1234
    ports:
      - "3307:3306"
    volumes:
      - shared-data:/cont/dbsql
      - ./init:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root1234

volumes:
  shared-data:
